apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: mlflow-store
          persistentVolumeClaim:
            claimName: mlflow-store
      serviceAccountName: {{ include "mlflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag }}"
          imagePullPolicy: {{ .Values.proxyImage.pullPolicy }}
          args:
            - "http://localhost/"
            - "{{ .Values.proxyConfig.rootDir }}"
            - "{{ .Values.proxyConfig.port }}"
          ports:
            - name: proxy
              containerPort: {{ .Values.proxyConfig.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: proxy
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: proxy
          resources:
            {{- toYaml .Values.proxyConfig.resources | nindent 12 }}
          env:
           - name: DOMINO_API_HOST
             value: "http://nucleus-frontend.domino-platform:80"
          {{ if .Values.awsAccessKeyID}}
          {{ if .Values.awsDefaultRegion}}
           - name: AWS_ACCESS_KEY_ID
             value: {{.Values.awsAccessKeyID}}
           - name: AWS_DEFAULT_REGION
             value: {{.Values.awsDefaultRegion}}
          {{end}}
          {{end}}
          volumeMounts:
            - mountPath: "/mnt/mlflow"
              name: mlflow-store
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --host=0.0.0.0
            - --port=80
          {{- if .Values.backendStore.filepath }}
            - --backend-store-uri={{ .Values.backendStore.filepath }}
          {{- else if .Values.backendStore.postgres }}
            - --backend-store-uri=postgresql://{{ required "you must specify a username for the database" .Values.backendStore.postgres.username }}:$(SECRET_PASSWORD)@{{ required "you must specify a host for the database" .Values.backendStore.postgres.host }}:{{ required "you must specify a port for the database" .Values.backendStore.postgres.port }}/{{ required "you must specify a database name" .Values.backendStore.postgres.database }}
          {{- end }}
          {{- if .Values.defaultArtifactRoot }}
            - --default-artifact-root={{ .Values.defaultArtifactRoot }}
          {{- end }}
          {{- if .Values.prometheus.expose }}
            - --expose-prometheus=yes
          {{- end }}
          {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          {{- if .Values.backendStore.postgres }}
          env:
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.postgresSecretName" . }}
                  key: password
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.awsSecretAccessKey" . }}
                  key: awsSecretAccessKey
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/mnt/mlflow"
              name: mlflow-store
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
