apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          domino-platform: "true"
  podSelector: 
    matchLabels:
        app.kubernetes.io/instance: mlflow
  policyTypes:
  - Ingress
  - Egress