apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}