{{- if .Values.backendStore.postgres -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.postgresSecretName" . }}
type: Opaque
data:
  password: {{ required "you must specify a database password" .Values.backendStore.postgres.password | b64enc }}
{{- end }}
{{- if .Values.awsSecretAccessKey -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.awsSecretAccessKey" . }}
type: Opaque
data:
  awsSecretAccessKey: {{ required "you must specify an awsSecretAccessKey" .Values.awsSecretAccessKey | b64enc }}
{{- end }}
