{{- if .Values.backendStore.postgres -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.postgresSecretName" . }}
type: Opaque
data:
  password: {{ required "you must specify a database password" .Values.backendStore.postgres.password | b64enc }}
{{- end }}
{{- if .Values.aws.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.awsSecretAccessKey" . }}
type: Opaque
data:
  awsAccessKeyID: {{ .Values.aws.accessKeyID | b64enc }}
  awsSecretAccessKey: {{ .Values.aws.secretAccessKey | b64enc }}
{{- end }}
